application:
  security:
    frontend-url: ${FRONTEND_URL}
  exchange:
    rate:
      url: ${EXCHANGE_RATE_URL}
      api-key: ${EXCHANGE_RATE_API_KEY}

aws:
  profile: ${AWS_PROFILE}
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    expiration-time: ${AWS_S3_PRESIGNED_URL_EXPIRATION_TIME}
  cloudfront:
    url: ${AWS_CLOUDFRONT_URL}
    public-key-pair-id: ${AWS_CLOUDFRONT_PUBLIC_KEY_PAIR_ID}
    private-key: ${AWS_CLOUDFRONT_PRIVATE_KEY}
  cognito:
    jwks-url: ${AWS_COGNITO_PUBLIC_KEY}
  transaction-response-url-type: cloudfront-signed

server:
  port: ${PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=24h

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false