application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY_DEV}
      expiration-time: 604800000
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account
      reset-url: http://localhost:5173/password-reset
  exchange:
    rate:
      url: ${EXCHANGE_RATE_URL}
      api-key: ${EXCHANGE_RATE_API_KEY}

aws:
  profile: ${AWS_PROFILE_DEV}
  s3:
    region: ${AWS_S3_REGION_DEV}
    bucket: ${AWS_S3_BUCKET_DEV}
    expiration-time: ${AWS_S3_PRESIGNED_URL-EXPIRATION_TIME_DEV}
  cloudfront:
    url: ${AWS_CLOUDFRONT_URL_DEV}
  transaction-response-url-type: ${AWS_URL_TYPE_DEV}

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST_DEV}
    port: 1025
    username: ${EMAIL_USERNAME_DEV}
    password: ${EMAIL_PASSWORD_DEV}
    default-encoding: UTF-8
    test-connection: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    default-encoding: UTF-8
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]