application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 604800
  mailing:
    frontend:
      activation-url: https://home-budget-tracker.vercel.app/activate-account
      reset-url: https://home-budget-tracker.vercel.app/password-reset
  exchange:
    rate:
      url: ${EXCHANGE_RATE_URL}
      api-key: ${EXCHANGE_RATE_API_KEY}

server:
  port: ${PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]