application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY_DEV}
      expiration-time: 604800000
  mailing:
    frontend:
      activation-url: http://localhost:5173/activate-account

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST_DEV}
    port: 1025
    username: ${EMAIL_USERNAME_DEV}
    password: ${EMAIL_PASSWORD_DEV}
    default-encoding: UTF-8
    test-connection: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    default-encoding: UTF-8
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]