application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:8080/activate-account

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    test-connection: true
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]

logging:
  file:
    path: ${LOG_FILE_PATH}
    name: ${logging.file.path}${LOG_FILE_NAME}