application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 604800
  mailing:
    frontend:
      activation-url: https://home-budget-tracker.vercel.app/activate-account

server:
  port: ${PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    test-connection: false
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]