name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SPRING_PROFILES_ACTIVE: test
  DB_NAME_DEV: testdb
  DB_USERNAME_DEV: testuser
  DB_PASSWORD_DEV: testpassword

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ env.DB_NAME_DEV }}
          POSTGRES_USER: ${{ env.DB_USERNAME_DEV }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD_DEV }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 and Cache Maven packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn clean test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: home-budget-tracker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          echo "heroku installed"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
